server.port=8080
spring.application.name=ewm-service

spring.datasource.url=jdbc:postgresql://localhost:5432/ewm
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

stats-server.url=${STATS_SERVER_URL:http://localhost:9090}
